SET(GVSOC_LIB_DIR ${CMAKE_CURRENT_LIST_DIR})
SET(GVSOC_TARGET_LIB_DIR ${GVSOC_LIB_DIR}/target/pulpissimo)

MACRO(GVSOC_PULPISSIMO_SETTINGS_PRE)
    SET(GVSOC_PULPISSIMO_INCLUDES
            ${GVSOC_TARGET_LIB_DIR}/include
            ${GVSOC_LIB_DIR}/target/arch
            ${GVSOC_LIB_DIR}/libc/malloc/include
            ${GVSOC_LIB_DIR}/drivers/include
    )

    SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)
ENDMACRO()

MACRO(GVSOC_PULPISSIMO_SETTINGS_POST TARGET_NAME)
    TARGET_INCLUDE_DIRECTORIES(${TARGET_NAME} PUBLIC ${GVSOC_PULPISSIMO_INCLUDES})
ENDMACRO()

MACRO(ADD_LIBRARY_GVSOC_PULPISSIMO TARGET_NAME)
    GVSOC_PULPISSIMO_SETTINGS_PRE()

    SET(ARGS "${ARGN}")
    SET(SRC_FILES ${ARGS})
    ADD_LIBRARY(${TARGET_NAME} ${SRC_FILES})

    GVSOC_PULPISSIMO_SETTINGS_POST(${TARGET_NAME})
ENDMACRO()

MACRO(ADD_EXECUTABLE_GVSOC_PULPISSIMO_INTERNAL TARGET_NAME ADD_PLATFORM_FILES)
    GVSOC_PULPISSIMO_SETTINGS_PRE()

    # prevent linker argument duplicates when calling macro for multiple targets
    IF(NOT GVSOC_PULPISSIMO_MACRO_ALREADY_EXECUTED)
        SET(CMAKE_EXE_LINKER_FLAGS
            "${CMAKE_EXE_LINKER_FLAGS} -nostartfiles \
            -T ${GVSOC_TARGET_LIB_DIR}/link.ld \
            "
        )
    ENDIF()

    PROJECT(${TARGET_NAME} LANGUAGES C CXX ASM)

    SET(ARGS "${ARGN}")
    SET(SRC_FILES ${ARGS})
    IF(${ADD_PLATFORM_FILES})
        LIST(APPEND SRC_FILES 
            ${GVSOC_TARGET_LIB_DIR}/system_metal.c
            ${GVSOC_TARGET_LIB_DIR}/crt0.S
            ${GVSOC_TARGET_LIB_DIR}/vectors_metal.S
	        ${GVSOC_LIB_DIR}/libc/malloc/malloc_internal.c
            ${GVSOC_LIB_DIR}/libc/malloc/cl_l1_malloc.c
            ${GVSOC_LIB_DIR}/libc/syscalls.c
            ${GVSOC_LIB_DIR}/libc/pulp_malloc.c              
        )
    ENDIF()

    ADD_EXECUTABLE(${TARGET_NAME} ${SRC_FILES})
    
    GVSOC_PULPISSIMO_SETTINGS_POST(${TARGET_NAME})
ENDMACRO()

MACRO(ADD_EXECUTABLE_GVSOC_PULPISSIMO TARGET_NAME)
    ADD_EXECUTABLE_GVSOC_PULPISSIMO_INTERNAL(${TARGET_NAME} ON ${ARGN})
ENDMACRO()

MACRO(ADD_EXECUTABLE_GVSOC_PULPISSIMO_RAW TARGET_NAME)
    ADD_EXECUTABLE_GVSOC_PULPISSIMO_INTERNAL(${TARGET_NAME} OFF ${ARGN})
ENDMACRO()
