MESSAGE(STATUS "ANDES")

IF(NOT ANDES_LIBNN_DIR)
    MESSAGE(FATAL_ERROR "Missing value: ANDES_LIBNN_DIR")
ENDIF()

SET(ANDES_LIBNN_LIB ${ANDES_LIBNN_DIR}/libnn_rvp32.a)

# TFLite integration
IF(TFLM_OPTIMIZED_KERNEL_LIB)
    LIST(APPEND TFLM_OPTIMIZED_KERNEL_LIB ${ANDELS_LIBNN_LIB})
ELSE()
    SET(TFLM_OPTIMIZED_KERNEL_LIB ${ANDES_LIBNN_LIB})
ENDIF()

IF(TFLM_OPTIMIZED_KERNEL_INCLUDE_DIR)
    LIST(APPEND TFLM_OPTIMIZED_KERNEL_INCLUDE_DIR ${ANDES_LIBNN_INCLUDE_DIRS})
ELSE()
    SET(TFLM_OPTIMIZED_KERNEL_INCLUDE_DIR ${ANDES_LIBNN_INCLUDE_DIRS})
ENDIF()

# IF(TFLM_OPTIMIZED_KERNEL_DEPS)
#     LIST(APPEND TFLM_OPTIMIZED_KERNEL_DEPS andes_libnn)
# ELSE()
#     SET(TFLM_OPTIMIZED_KERNEL_DEPS andes_libnn)
# ENDIF()
