SET(LLVM_BASIC_BLOCK_SECTIONS OFF CACHE BOOL "Enable LLVMs -fbasic-block-sections=labels (custom)")
IF(LLVM_BASIC_BLOCK_SECTIONS)
    IF(NOT ${TOOLCHAIN} STREQUAL "llvm")
        MESSAGE(FATAL_ERROR "llvm_basic_block_sections feature needs llvm toolchain")
    ENDIF()
    LIST(APPEND LLVMBB_FLAGS "-fbasic-block-sections=labels")
    LIST(APPEND FEATURE_EXTRA_C_FLAGS ${LLVMBB_FLAGS})
    LIST(APPEND FEATURE_EXTRA_CXX_FLAGS ${LLVMBB_FLAGS})
ENDIF()
