IF("${MLONMCU_FRAMEWORK}" STREQUAL "")
    SET(MLONMCU_FRAMEWORK "executorch")
ENDIF()

SET(EXECUTORCH_REQUIRED_COMPONENTS a b c)

SET(EXECUTORCH_LIB executorch)
SET(EXECUTORCH_WRAPPER_FILENAME executorch_wrapper.cc)
