#SET(CMAKE_C_COMPILER ${TC_PREFIX}gcc${EXE_EXT})
#SET(CMAKE_CXX_COMPILER ${TC_PREFIX}g++${EXE_EXT})
#SET(CMAKE_ASM_COMPILER ${TC_PREFIX}gcc${EXE_EXT})
#SET(CMAKE_LINKER ${TC_PREFIX}ld${EXE_EXT})
#SET(CMAKE_OBJCOPY ${TC_PREFIX}objcopy${EXE_EXT})
#SET(CMAKE_AR ${TC_PREFIX}ar${EXE_EXT})
#SET(CMAKE_RANLIB ${TC_PREFIX}ranlib${EXE_EXT})

SET(CMAKE_C_COMPILER /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-gcc)
SET(CMAKE_CXX_COMPILER /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-g++)
SET(CMAKE_ASM_COMPILER /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-gcc)
SET(CMAKE_LINKER /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-ld)
SET(CMAKE_OBJCOPY /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-objcopy)
SET(CMAKE_AR /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-ar)
SET(CMAKE_RANLIB /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-ranlib)