SET(TGC_PREFIX "/opt/shared/cross-toolchains/gcc13/Ubuntu/riscv64-unknown-elf/bin/riscv64-unknown-elf-" CACHE PATH "install dir for our gcc")
SET(CMAKE_C_COMPILER ${TGC_PREFIX}gcc${EXE_EXT})
SET(CMAKE_CXX_COMPILER ${TGC_PREFIX}g++${EXE_EXT})
SET(CMAKE_ASM_COMPILER ${TGC_PREFIX}gcc${EXE_EXT})
SET(CMAKE_LINKER ${TGC_PREFIX}ld${EXE_EXT})
SET(CMAKE_OBJCOPY ${TGC_PREFIX}objcopy${EXE_EXT})
SET(CMAKE_AR ${TGC_PREFIX}ar${EXE_EXT})
SET(CMAKE_RANLIB ${TGC_PREFIX}ranlib${EXE_EXT})

#SET(CMAKE_C_COMPILER /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-gcc)
#SET(CMAKE_CXX_COMPILER /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-g++)
#SET(CMAKE_ASM_COMPILER /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-gcc)
#SET(CMAKE_LINKER /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-ld)
#SET(CMAKE_OBJCOPY /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-objcopy)
#SET(CMAKE_AR /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-ar)
#SET(CMAKE_RANLIB /opt/shared/cross-toolchains/gcc11/Ubuntu/riscv32-unknown-elf/bin/riscv32-unknown-elf-ranlib)