SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_PROCESSOR Pulpino)

SET(RISCV_ELF_GCC_PREFIX
    ""
    CACHE PATH "install location for riscv-gcc toolchain"
)
SET(RISCV_ELF_GCC_BASENAME
    "riscv64-unknown-elf"
    CACHE STRING "base name of the toolchain executables"
)
SET(RISCV_ARCH
    "rv32gc"
    CACHE STRING "march argument to the compiler"
)
# set(RISCV_ARCH "rv32gcv" CACHE STRING "march argument to the compiler")
SET(RISCV_ABI
    "ilp32d"
    CACHE STRING "mabi argument to the compiler"
)
SET(TC_PREFIX "${RISCV_ELF_GCC_PREFIX}/bin/${RISCV_ELF_GCC_BASENAME}-")

SET(ETISS_DIR
    ""
    CACHE STRING "Directory of ETISS"
)

SET(PULPINO_TC_DIR ${ETISS_DIR}/examples/SW/riscv/cmake)
ADD_DEFINITIONS(-DPULPINO_NO_GPIO)

SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PULPINO_TC_DIR}")
IF(NOT PULPINO_ROM_START)
    SET(PULPINO_ROM_START 0x0)
ENDIF()
IF(NOT PULPINO_ROM_SIZE)
    SET(PULPINO_ROM_SIZE 0x100000)
ENDIF()
IF(NOT PULPINO_RAM_START)
    SET(PULPINO_RAM_START 0x100000)
ENDIF()
IF(NOT PULPINO_RAM_SIZE)
    SET(PULPINO_RAM_SIZE 0x200000)
ENDIF()
SET(PULPINO_MIN_STACK_SIZE 0x4000)
SET(PULPINO_MIN_HEAP_SIZE 0x4000)
SET(ETISS_LOGGER_ADDR 0xf0000000)

INCLUDE(PulpinoTarget)
MACRO(COMMON_ADD_LIBRARY TARGET_NAME)
    ADD_LIBRARY_PULPINO(${TARGET_NAME} ${ARGN})
ENDMACRO()
MACRO(COMMON_ADD_EXECUTABLE TARGET_NAME)
    SET(ARGS "${ARGN}")
    SET(SRC_FILES ${ARGS})
    ADD_EXECUTABLE_PULPINO(${TARGET_NAME} ${ARGN})
ENDMACRO()

ADD_DEFINITIONS(-DBUILDING_FOR_ETISS)

ADD_DEFINITIONS(-D__riscv__)
ADD_DEFINITIONS(-march=${RISCV_ARCH})
ADD_DEFINITIONS(-mabi=${RISCV_ABI})
