SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_PROCESSOR Pulpino)

SET(RISCV_ELF_GCC_PREFIX
    ""
    CACHE PATH "install location for riscv-gcc toolchain"
)
SET(RISCV_ELF_GCC_BASENAME
    "riscv64-unknown-elf"
    CACHE STRING "base name of the toolchain executables"
)
SET(RISCV_ARCH
    "rv32gc"
    CACHE STRING "march argument to the compiler"
)
SET(RISCV_ABI
    "ilp32d"
    CACHE STRING "mabi argument to the compiler"
)
SET(TC_PREFIX "${RISCV_ELF_GCC_PREFIX}/bin/${RISCV_ELF_GCC_BASENAME}-")

IF(NOT MEM_ROM_ORIGIN)
    SET(MEM_ROM_ORIGIN 0x0)
ENDIF()
IF(NOT MEM_ROM_LENGTH)
    SET(MEM_ROM_LENGTH 0x10000000)
ENDIF()
IF(NOT MEM_RAM_ORIGIN)
    SET(MEM_RAM_ORIGIN 0x10000000)
ENDIF()
IF(NOT MEM_RAM_LENGTH)
    SET(MEM_RAM_LENGTH 0x100000)
ENDIF()
#
set(MIN_STACK_SIZE 0x4000)
set(MIN_HEAP_SIZE 0x4000)

SET(ETISS_LDSCRIPT ${CMAKE_CURRENT_BINARY_DIR}/etiss.ld)
SET(ETISS_LDFLAGS "-L${CMAKE_CURRENT_BINARY_DIR}/riscv_crt0 --specs=${CMAKE_CURRENT_LIST_DIR}/etiss/etiss-semihost.specs -T ${ETISS_LDSCRIPT}")

SET(ETISS_CRT_DIR ${CMAKE_CURRENT_LIST_DIR}/etiss)

MACRO(COMMON_ADD_EXECUTABLE TARGET_NAME)
	  SET(SRC_FILES "${ARGN}")
    ADD_SUBDIRECTORY(${ETISS_CRT_DIR} ${CMAKE_CURRENT_BINARY_DIR}/etiss_crt0)

	  ADD_EXECUTABLE(${TARGET_NAME} ${SRC_FILES})
	  ADD_DEPENDENCIES(${TARGET_NAME} etiss_crt0)
    SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${ETISS_LDFLAGS}")
    TARGET_LINK_LIBRARIES(${TARGET_NAME} PRIVATE etiss_crt0)
ENDMACRO()

ADD_DEFINITIONS(-D__riscv__)
ADD_DEFINITIONS(-march=${RISCV_ARCH})
ADD_DEFINITIONS(-mabi=${RISCV_ABI})

IF(RISCV_VEXT)
    ADD_DEFINITIONS(-DUSE_VEXT)
ENDIF()

CONFIGURE_FILE(${CMAKE_CURRENT_LIST_DIR}/etiss/etiss.ld.in etiss.ld @ONLY)
