SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_PROCESSOR gvsoc_pulp)

# SET(GVSOC_BASIC_CMAKE_DIR
#     ""
#     CACHE STRING "Directory of GVSOC basic cmake directory"
# )

# SET(GVSOC_PULP_TC_DIR ${ETISS_DIR}/examples/SW/riscv/cmake)
# ADD_DEFINITIONS(-DGVSOC_PULP_NO_GPIO)
# MESSAGE("CMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}")
# SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${GVSOC_BASIC_CMAKE_DIR}")
# IF(NOT GVSOC_PULP_ROM_START)
#     SET(GVSOC_PULP_ROM_START 0x0)
# ENDIF()
# IF(NOT GVSOC_PULP_ROM_SIZE)
#     SET(GVSOC_PULP_ROM_SIZE 0x100000)
# ENDIF()
# IF(NOT GVSOC_PULP_RAM_START)
#     SET(GVSOC_PULP_RAM_START 0x100000)
# ENDIF()
# IF(NOT GVSOC_PULP_RAM_SIZE)
#     SET(GVSOC_PULP_RAM_SIZE 0x200000)
# ENDIF()
# SET(GVSOC_PULP_MIN_STACK_SIZE 0x4000)
# SET(GVSOC_PULP_MIN_HEAP_SIZE 0x4000)
# SET(ETISS_LOGGER_ADDR 0xf0000000)

INCLUDE(targets/gvsoc/PulpTarget)
MACRO(COMMON_ADD_LIBRARY TARGET_NAME)
    ADD_LIBRARY_GVSOC_PULP(${TARGET_NAME} ${ARGN})
ENDMACRO()
MACRO(COMMON_ADD_EXECUTABLE TARGET_NAME)
    SET(ARGS "${ARGN}")
    SET(SRC_FILES ${ARGS})
    ADD_EXECUTABLE_GVSOC_PULP(${TARGET_NAME} ${ARGN})
ENDMACRO()

# The linker argument setting will break the cmake test program on 64-bit,
# so disable test program linking for now.
SET(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")
