IF(WIN32)
    MESSAGE(FATAL_ERROR "Windows target is not supported")
ELSEIF(APPLE)
    SET(CMAKE_SYSTEM_NAME Darwin)
ELSEIF(UNIX)
    SET(CMAKE_SYSTEM_NAME Linux)
ENDIF()

SET(CMAKE_SYSTEM_PROCESSOR x86_64)
