IF(NOT SRC_DIR)
    MESSAGE(FATAL_ERROR "The variable SRC_DIR is not set")
ENDIF()

SET(EXTRA_SRC ml_interface_executorch.cc)

SET(EXTRA_SRC ${EXTRA_SRC} ${SRC_DIR}/${EXECUTORCH_WRAPPER_FILENAME})
# TARGET_LINK_LIBRARIES(${EXECUTORCH_LIB} PUBLIC m)
SET(EXTRA_INC ${SRC_DIR})

SET(EXTRA_LIBS )
