IF(NOT SRC_DIR)
	MESSAGE(FATAL_ERROR "The variable SRC_DIR is not set")
ENDIF()

FILE(GLOB NONE_SRCS ${SRC_DIR}/*.c ${SRC_DIR}/*.cc)
SET(EXTRA_SRCS ${EXTRA_SRC} ${NONE_SRCS})
SET(EXTRA_INCS ${EXTRA_INC} ${SRC_DIR})
SET(EXTRA_LIBS ${EXTRA_LIBS} m)
